// Copyright 2026 The ijkpp Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// Values marked "ported" come from ijkplayer's ff_ffplay_def.h and must be
// regenerated by tools/extract_constants.py, never retyped by hand. See
// docs/05 table 7 and docs/01 §6 (algorithms and thresholds are inherited,
// not "improved").

#ifndef IJKPP_MEDIA_BASE_MEDIA_CONSTANTS_H_
#define IJKPP_MEDIA_BASE_MEDIA_CONSTANTS_H_

#include <cstddef>
#include <cstdint>

#include "base/time/time.h"

namespace ijkpp::media {

// Sentinel for "this timestamp does not exist", replacing the AV_NOPTS_VALUE
// magic number that ijkplayer passes around as a bare int64. Using TimeDelta's
// minimum keeps every comparison well defined: kNoTimestamp sorts before any
// real timestamp, and arithmetic involving it is checked explicitly rather
// than silently overflowing.
inline constexpr base::TimeDelta kNoTimestamp = base::TimeDelta::Min();

inline bool IsNoTimestamp(base::TimeDelta t) {
  return t.is_min() || t.is_max();
}

// ---- Buffer / queue sizing -------------------------------------------------
// Ported: MAX_QUEUE_SIZE.
inline constexpr size_t kDefaultMaxBufferBytes = 15 * 1024 * 1024;
// Ported: DEFAULT_MIN_FRAMES / MIN_MIN_FRAMES / MAX_MIN_FRAMES.
inline constexpr size_t kDefaultMinFrames = 5;
inline constexpr size_t kMinMinFrames = 2;
inline constexpr size_t kMaxMinFrames = 50;
// Ported: VIDEO_PICTURE_QUEUE_SIZE_DEFAULT / MIN / MAX.
inline constexpr int kVideoFrameQueueSizeDefault = 3;
inline constexpr int kVideoFrameQueueSizeMin = 2;
inline constexpr int kVideoFrameQueueSizeMax = 16;
// Ported: AUDIO_PICTURE_QUEUE_SIZE_DEFAULT.
inline constexpr int kAudioFrameQueueSizeDefault = 9;
inline constexpr int kTextFrameQueueSizeDefault = 16;

// ---- DecoderStream watermarks ---------------------------------------------
// Not ported: these follow Chromium's media/filters/decoder_stream.h, which
// bounds in-flight decodes so a hardware decoder is never starved or flooded.
inline constexpr size_t kDecoderStreamLowWaterMark = 4;
inline constexpr size_t kDecoderStreamSelectedWaterMark = 8;
inline constexpr int kDecoderStreamMaxDecodeRequests = 4;
// Number of buffers requested per DemuxerStream::Read() call.
inline constexpr uint32_t kDecoderStreamReadChunk = 4;

// ---- Playback limits -------------------------------------------------------
inline constexpr double kMinPlaybackRate = 0.25;
inline constexpr double kMaxPlaybackRate = 4.0;
// Ported: max-fps option range.
inline constexpr int kMaxFpsDisabled = -1;
inline constexpr int kMaxFpsDefault = 31;
inline constexpr int kMaxFpsLimit = 121;
// Ported: framedrop option range.
inline constexpr int kFrameDropDisabled = -1;
inline constexpr int kFrameDropDefault = 0;
inline constexpr int kFrameDropLimit = 120;

// ---- Diagnostics -----------------------------------------------------------
inline constexpr size_t kStateHistoryCapacity = 64;
inline constexpr size_t kMediaLogEventCapacity = 256;

}  // namespace ijkpp::media

#endif  // IJKPP_MEDIA_BASE_MEDIA_CONSTANTS_H_
