// Copyright 2026 The avbase Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef AVBASE_PLAYER_PUBLIC_VERSION_H_
#define AVBASE_PLAYER_PUBLIC_VERSION_H_

#include "avbase/Version.h"  // Generated by CMake.

namespace avbase {

// Stable version string, e.g. "0.1.0".
const char* GetVersionString();

}  // namespace avbase

#endif  // AVBASE_PLAYER_PUBLIC_VERSION_H_
