// Copyright 2026 The ijkpp Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef IJKPP_PLAYER_PUBLIC_VERSION_H_
#define IJKPP_PLAYER_PUBLIC_VERSION_H_

#include "ijkpp/Version.h"   // Generated by CMake.

namespace ijkpp {

// Stable version string, e.g. "0.1.0".
const char* GetVersionString();

}  // namespace ijkpp

#endif  // IJKPP_PLAYER_PUBLIC_VERSION_H_
