#!/usr/bin/env python3
# Copyright 2026 The avbase Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Cross-checks every ported ffplay threshold against all of its sources.

Risk R1 (docs/08 §5, P4 x I5 = 20) is the only entry in the risk register that
can fail the whole project: a subtly wrong A/V-sync threshold produces
"occasionally out of sync" reports that no unit test reproduces. Mitigation 4
for R1 reads, verbatim:

    阈值用 extract_constants.py 提取，禁止手抄

Until now that tool did not exist, and every threshold in
media/filters/legacy/av_sync_controller.h, .../video_frame_compositor.h,
media/base/media_constants.h and player/public/player_config.h WAS hand-typed
-- while media_constants.h's own header comment already said the values "must
be regenerated by tools/extract_constants.py, never retyped by hand". This
script is that mitigation.

It cross-checks up to three sources per constant:

    ffplay source (#define)  <->  avbase code  <->  docs/05 table 7

and exits non-zero on any disagreement, so a fat-fingered 0.04 -> 0.4, or a
fork that genuinely uses a different DEFAULT_MIN_FRAMES, becomes a CI failure
instead of a sync bug discovered in production.

Units are declared, never guessed
---------------------------------
ffplay is not self-consistent: AV_SYNC_THRESHOLD_MIN is 0.04 (seconds) while
MAX_SLEEP is 1000000 (microseconds), and AV_NOSYNC_THRESHOLD is 10.0 -- an
*integral* number of seconds, which no "is it a float?" heuristic can tell
apart from 10 of something else. So each SPEC entry declares `source_unit`,
the unit the ffplay/docs literal is written in. The avbase side needs no hint:
`base::Seconds(10)` / `base::Milliseconds(40)` / `base::Microseconds(500)`
carry their own unit, and a bare literal in media_constants.h is already in the
canonical unit.

Usage
-----
    # No ijkplayer checkout needed: validates the parser against a synthetic
    # ffplay snippet and runs the avbase <-> docs/05 check. CI-safe.
    tools/extract_constants.py --selftest

    # Full three-way check against a real ijkplayer tree.
    tools/extract_constants.py --ijkplayer /path/to/ijkplayer

    # Machine readable, for tools/golden_diff.py and CI annotations.
    tools/extract_constants.py --selftest --json

    # Emit the provenance block for media/base/media_constants.h (M13).
    tools/extract_constants.py --ijkplayer /path/to/ijkplayer --emit

Deliberate deviations (Δ4) and avbase-only constants are declared in SPEC rather
than silently skipped, so the report always accounts for every entry.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from ported_constants import (  # noqa: E402  (path set above)
    DOCS_TABLE,
    FATAL,
    FFPLAY_FILES,
    SPEC,
    SELFTEST_CANON,
    SELFTEST_DEFINES,
    SELFTEST_EXPECT,
    TIME_UNITS,
    UNITS_PER_SECOND,
    BASE_TIME_KINDS,
    Spec,
    canonicalise,
    convert,
)

# ---------------------------------------------------------------------------
# Parsing primitives
# ---------------------------------------------------------------------------

DEFINE_RE = re.compile(r"^\s*#\s*define\s+(\w+)\s+(.+?)\s*$")
CONSTEXPR_RE = re.compile(
    r"inline\s+constexpr\s+[\w:<>,\s]+?\s(\w+)\s*=\s*([^;]+);")
# A default member initialiser: "base::TimeDelta x{base::Seconds(5)};",
# "int frame_queue_size{3};", "double coef{0.9};". Requiring the brace-or-equals
# is what keeps this from matching a declaration such as
# "inline constexpr size_t kFoo" whose initialiser is on the same line but is
# handled by CONSTEXPR_RE instead.
# The type may be several tokens long and may carry an export macro
# ("struct AVBASE_PLAYER_EXPORT BufferConfig" / "base::TimeDelta
# first_high_water_mark{...}"), so every token before the last is
# swallowed as type-or-macro and only the last one is the field name.
FIELD_RE = re.compile(
    r"^(?:[\w:]+\s+)+(\w+)\s*(?:\{([^{}]*)\}|=\s*([^;]+))")
STRUCT_RE = re.compile(r"\s*(?:struct|class)\s+(\w+)(?:\s+(\w+))?")
BASE_TIME_RE = re.compile(
    r"base::(Seconds|Milliseconds|Microseconds)\(\s*([^()]*?)\s*\)")
TRAILING_MACRO_RE = re.compile(r"([A-Z][A-Z0-9_]{3,})\s*$")
NUM_RE = re.compile(
    r"[+-]?(?:0[xX][0-9a-fA-F]+|\d+\.?\d*(?:[eE][+-]?\d+)?|\.\d+)[uUlLfF]*")
IDENT_RE = re.compile(r"[A-Za-z_]\w*")
CAST_RE = re.compile(
    r"\(\s*(?:unsigned\s+|signed\s+|const\s+)*"
    r"(?:int64_t|uint64_t|int32_t|size_t|double|float|int|long|unsigned)\s*\)\s*")
SAFE_EXPR_RE = re.compile(r"[0-9eExXa-fA-F.+\-*/%() ]+\Z")


def strip_comments(text: str) -> str:
    """Removes // and /* */ comments while preserving line structure."""
    text = re.sub(r"/\*.*?\*/", lambda m: "\n" * m.group(0).count("\n"), text,
                  flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def tail_comment(line: str) -> str:
    m = re.search(r"//\s*(.*)$", line)
    return m.group(1).strip() if m else ""


def eval_expr(expr: str, macros: dict, depth: int = 0):
    """Evaluates a C constant expression. Returns int/float, or None when the
    expression is not a compile-time constant we model (function-like macro,
    reference to something undefined, exotic cast)."""
    if depth > 16:
        return None
    expr = CAST_RE.sub("", expr).strip()
    if not expr:
        return None
    out, i, n = [], 0, len(expr)
    while i < n:
        ch = expr[i]
        if ch.isspace():
            i += 1
            continue
        m = NUM_RE.match(expr, i)
        if m:
            out.append(m.group(0).rstrip("uUlLfF"))
            i = m.end()
            continue
        m = IDENT_RE.match(expr, i)
        if m:
            name = m.group(0)
            i = m.end()
            if name in ("defined", "if", "ifdef", "ifndef", "endif", "else"):
                return None
            if name not in macros:
                return None
            value = eval_expr(macros[name], macros, depth + 1)
            if value is None:
                return None
            out.append(repr(float(value)))
            continue
        out.append(ch)
        i += 1
    candidate = " ".join(out)
    if not SAFE_EXPR_RE.match(candidate):
        return None
    try:
        value = eval(candidate, {"__builtins__": {}}, {})  # noqa: S307
    except Exception:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return value


def parse_defines(text: str) -> dict:
    """Collects every object-like #define; values resolve lazily."""
    macros = {}
    for raw in text.splitlines():
        if raw.rstrip().endswith("\\"):
            continue
        m = DEFINE_RE.match(strip_comments(raw))
        if m:
            macros.setdefault(m.group(1), m.group(2))
    return macros


def resolve(macros: dict, name: str):
    return eval_expr(macros[name], macros) if name in macros else None


# ---------------------------------------------------------------------------
# avbase side
# ---------------------------------------------------------------------------

def parse_time_or_number(body: str):
    """Returns (value, kind) for a field initialiser body.

    |body| is the whole initialiser, so "15 * 1024 * 1024" evaluates to the
    product rather than to its first token, and "base::Seconds(5)" reports the
    unit it was written in.
    """
    m = BASE_TIME_RE.search(body)
    if m:
        inner = eval_expr(m.group(2), {})
        return (inner, m.group(1)) if inner is not None else (None, "")
    return eval_expr(body, {}), ""


def scan_one_file(rel: str, text: str) -> dict:
    """Returns {(rel, symbol): (raw_value, kind)} for all three shapes a ported
    constant takes: an inline constexpr, a default member initialiser, or a bare
    literal whose trailing comment names the ffplay macro."""
    found: dict = {}
    clean = strip_comments(text).splitlines()
    # Join physical lines into statements (see gen_options.py's note): a
    # wrapped default member initialiser ("base::TimeDelta accurate_timeout{\n
    # base::Seconds(5)};") is one constant, and the one-line FIELD_RE below
    # used to miss it -- NOT_IN_AVBASE on a value that is right there.
    stmts: list[tuple[str, str]] = []
    buf_raw = buf_code = ""
    for raw, code in zip(text.splitlines(), clean):
        buf_raw = f"{buf_raw}\n{raw}" if buf_raw else raw
        buf_code = f"{buf_code}\n{code}" if buf_code else code
        stripped = buf_code.strip()
        if stripped.endswith(";") or (
            stripped.endswith("{")
            and re.match(r"(namespace|struct|class|enum|union)\b", stripped)):
            stmts.append((buf_raw, buf_code))
            buf_raw = buf_code = ""
    if buf_code.strip():
        stmts.append((buf_raw, buf_code))
    scope = ""
    for raw, code in stmts:
        # "struct AVBASE_PLAYER_EXPORT BufferConfig {" -- the export macro is a
        # token, not the name, so skip every ALL-CAPS token after struct/class.
        m = STRUCT_RE.match(code)
        if m:
            scope = m.group(2) or m.group(1)
            continue
        m = CONSTEXPR_RE.search(code)
        if m:
            value = eval_expr(m.group(2), {})
            if value is not None:
                found[(rel, m.group(1))] = (value, "")
            continue
        field = FIELD_RE.match(code.strip())
        if field:
            value, kind = parse_time_or_number(field.group(2) or field.group(3))
            if value is not None:
                name = field.group(1)
                if scope:
                    # Scoped only: two structs in one header legitimately have
                    # fields of the same name (VideoConfig::frame_queue_size vs
                    # AudioConfig::frame_queue_size) and they are different
                    # constants, so an unscoped key would silently pick one.
                    found[(rel, f"{scope}::{name}")] = (value, kind)
                else:
                    found[(rel, name)] = (value, kind)
        macro = TRAILING_MACRO_RE.search(tail_comment(raw))
        if macro:
            value, kind = parse_time_or_number(code)
            if value is not None:
                found[(rel, "@" + macro.group(1))] = (value, kind)
    return found


def scan_avbase(root: pathlib.Path, specs) -> dict:
    wanted = {path for spec in specs for path, _ in spec.avbase}
    found: dict = {}
    for rel in sorted(wanted):
        path = root / rel
        if path.exists():
            found.update(scan_one_file(
                rel, path.read_text(encoding="utf-8", errors="replace")))
    return found


def lookup_avbase(found, spec):
    """Returns (canonical value or None, detail). Every declared location must
    agree -- media_constants.h and player_config.h holding different values for
    the same ported macro is exactly the drift this tool exists to catch."""
    values = []
    for rel, symbol in spec.avbase:
        entry = found.get((rel, symbol))
        if entry is None and spec.macro:
            entry = found.get((rel, "@" + spec.macro))
        values.append(None if entry is None
                      else canonicalise(entry[0], entry[1], spec.unit))
    if not values or all(v is None for v in values):
        return None, "not found"
    known = [v for v in values if v is not None]
    if any(not compare(known[0], v, spec.unit) for v in known[1:]):
        detail = ", ".join(f"{sym}={fmt(v)}"
                           for (_, sym), v in zip(spec.avbase, values))
        return known[0], f"locations disagree: {detail}"
    missing = [sym for (_, sym), v in zip(spec.avbase, values) if v is None]
    return known[0], ("missing in " + ", ".join(missing)) if missing else ""


# ---------------------------------------------------------------------------
# docs/05 table 7 side
# ---------------------------------------------------------------------------

def parse_docs(root: pathlib.Path) -> dict:
    """Pulls the numbers out of each table-7 row. Deliberately loose: a row may
    list several macros ("3 / 2 / 16") or an expression ("15*1024*1024"), and
    the goal is to catch a fat-fingered 0.04 -> 0.4, not to re-parse markdown."""
    path = root / DOCS_TABLE
    if not path.exists():
        return {}
    out = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 2:
            continue
        names = tuple(re.findall(r"`([A-Z][A-Z0-9_]{3,})`", cells[0]))
        if not names:
            continue
        values = []
        for expr in re.split(r"[/、,]|\s+or\s+", cells[1].replace("`", "")):
            expr = re.sub(r"[（(][^)）]*[)）]", "", expr).strip()
            if not expr:
                continue
            evaluated = eval_expr(expr, {})
            if evaluated is not None:
                values.append(float(evaluated))
        for name in names:
            previous = out.get(name)
            # An unambiguous single-macro row wins over a shared multi-macro row.
            if previous is None or (len(names) == 1 and len(previous[0]) > 1):
                out[name] = (names, values)
    return out


# ---------------------------------------------------------------------------
# Checking
# ---------------------------------------------------------------------------

def compare(a, b, unit) -> bool:
    if a is None or b is None:
        return False
    a, b = float(a), float(b)
    if unit == "r":
        return abs(a - b) <= max(1e-9, abs(b) * 1e-6)
    return abs(a - b) <= max(1e-6, abs(b) * 1e-9)


def check(root: pathlib.Path, ffplay_macros):
    found = scan_avbase(root, SPEC)
    docs = parse_docs(root)
    return [check_one(spec, found, docs, ffplay_macros) for spec in SPEC]


def check_one(spec, found, docs, ffplay_macros):
    row = {"macro": spec.macro or "(avbase-only)", "unit": spec.unit,
           "ffplay": None, "avbase": None, "docs": None, "status": "OK",
           "note": spec.note, "where": [s for _, s in spec.avbase]}
    if spec.macro and ffplay_macros is not None:
        raw = resolve(ffplay_macros, spec.macro)
        if raw is None:
            row["status"] = "NOT_IN_FFP"
        else:
            row["ffplay"] = canonicalise(raw, "", spec.unit, spec.source_unit)
    if spec.avbase:
        row["avbase"], detail = lookup_avbase(found, spec)
        if row["avbase"] is None:
            row["status"] = "NOT_IN_AVBASE"
        elif detail.startswith("locations disagree"):
            row["status"] = "LOCATIONS_DISAGREE"
        if detail and not detail.startswith("locations disagree"):
            row["note"] = join_note(row["note"], detail)
    check_docs(row, spec, docs)
    if spec.deviation:
        row["status"] = f"DEVIATION {spec.deviation}"
    elif not spec.avbase:
        # Nothing on the avbase side to compare against yet. Distinct from OK so
        # the summary cannot claim a constant was verified when it was not.
        row["status"] = "NO_AVBASE_SYMBOL"
    elif row["status"] == "OK":
        finalise(row, spec)
    return row


def check_docs(row, spec, docs):
    if not (spec.macro and docs):
        return
    entry = docs.get(spec.macro)
    if entry is None:
        row["note"] = join_note(row["note"], "macro absent from docs/05 table 7")
        return
    names, values = entry
    row["docs"] = [convert(v, spec.source_unit, spec.unit) for v in values]
    if spec.docs is None:
        return
    expected = canonicalise(float(spec.docs), "", spec.unit, spec.source_unit)
    if any(compare(expected, v, spec.unit) for v in row["docs"]):
        return
    if len(names) == 1 and len(values) == 1:
        row["status"] = "DOCS_MISMATCH"
    else:
        row["note"] = join_note(
            row["note"],
            f"docs/05 row is ambiguous ({'/'.join(names)} = "
            f"{fmt_list(row['docs'])}); expected {fmt(expected)}")


def finalise(row, spec):
    if row["ffplay"] is not None and row["avbase"] is not None:
        if not compare(row["ffplay"], row["avbase"], spec.unit):
            row["status"] = "MISMATCH"
    elif row["avbase"] is not None and spec.docs is not None:
        expected = canonicalise(float(spec.docs), "", spec.unit, spec.source_unit)
        if not compare(expected, row["avbase"], spec.unit):
            row["status"] = "MISMATCH_VS_DOCS"


def join_note(existing: str, extra: str) -> str:
    return f"{existing} | {extra}" if existing else extra


def fmt(value):
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def fmt_list(values) -> str:
    return ",".join(fmt(v) for v in values[:6]) if values else "-"


def print_report(rows) -> int:
    width = max(len(r["macro"]) for r in rows)
    print(f"{'macro':<{width}}  {'unit':>4}  {'ffplay':>12}  {'avbase':>12}  "
          f"{'docs/05':>14}  status")
    for r in rows:
        print(f"{r['macro']:<{width}}  {r['unit']:>4}  {fmt(r['ffplay']):>12}  "
              f"{fmt(r['avbase']):>12}  {fmt_list(r['docs']):>14}  {r['status']}")
    notes = [r for r in rows if r["note"]]
    if notes:
        print()
        for r in notes:
            print(f"  note {r['macro']}: {r['note']}")
    bad = [r for r in rows if r["status"] in FATAL]
    print()
    if bad:
        print(f"extract_constants: {len(bad)} disagreement(s) -- thresholds are "
              f"ported, not tuned (docs/05 table 7; docs/08 risk R1, "
              f"mitigation 4)")
        return 1
    ok = sum(1 for r in rows if r["status"] == "OK")
    dev = sum(1 for r in rows if r["status"].startswith("DEVIATION"))
    pending = sum(1 for r in rows if r["status"] == "NO_AVBASE_SYMBOL")
    uncheckable = len(rows) - ok - dev - pending
    mode = "three-way" if any(r["ffplay"] is not None for r in rows) \
        else "two-way (no --ijkplayer: ffplay side not read)"
    print(f"extract_constants: {ok} constant(s) agree [{mode}], "
          f"{dev} declared deviation(s), {pending} with no avbase symbol yet, "
          f"{uncheckable} unaccounted")
    return 0


def emit_block(rows) -> str:
    out = ["// GENERATED BY tools/extract_constants.py --emit. DO NOT EDIT.",
           "// Source of truth: the ffplay headers in the checkout passed to",
           "// --ijkplayer. Regenerate instead of retyping (docs/08 risk R1,",
           "// mitigation 4: thresholds are extracted, never hand-copied)."]
    for r in rows:
        if r["avbase"] is None:
            continue
        out.append(f"// {r['macro']} [{r['unit']}]: ffplay={fmt(r['ffplay'])} "
                   f"avbase={fmt(r['avbase'])} docs/05={fmt_list(r['docs'])} "
                   f"({', '.join(r['where'])}) [{r['status']}]")
    return "\n".join(out)

def selftest_macros() -> list:
    macros = parse_defines(SELFTEST_DEFINES)
    failures = []
    for name, want in SELFTEST_EXPECT:
        got = resolve(macros, name)
        if not compare(want, got, "r"):
            failures.append(f"{name}: want {want}, parser gave {got}")
    for name in ("FFMAX", "AV_NOPTS_VALUE"):
        if resolve(macros, name) is not None:
            failures.append(f"{name}: non-constant macro must not resolve")
    if "MAX_QUEUE_SIZE" not in macros:
        failures.append("parse_defines dropped a #define")
    for value, kind, unit, source, want in SELFTEST_CANON:
        got = canonicalise(value, kind, unit, source)
        if not compare(want, got, unit):
            failures.append(f"canonicalise({value}, {kind!r}, {unit!r}, "
                            f"{source!r}) = {got}, want {want}")
    return failures


def load_ffplay_macros(ijkplayer_root: pathlib.Path):
    files = []
    for name in FFPLAY_FILES:
        files.extend(p for p in ijkplayer_root.rglob(name) if p.is_file())
    if not files:
        return None, []
    macros: dict = {}
    for path in sorted(files):
        for key, value in parse_defines(
                path.read_text(encoding="utf-8", errors="replace")).items():
            macros.setdefault(key, value)
    return macros, sorted(files)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".", help="avbase repository root")
    parser.add_argument("--ijkplayer", default=None,
                        help="path to an ijkplayer/ffplay source tree")
    parser.add_argument("--selftest", action="store_true",
                        help="validate the parser, then run the avbase<->docs check")
    parser.add_argument("--json", action="store_true", help="machine readable")
    parser.add_argument("--emit", action="store_true",
                        help="print the generated provenance block")
    args = parser.parse_args()

    root = pathlib.Path(args.root)
    macros = None
    if args.ijkplayer:
        ijk_root = pathlib.Path(args.ijkplayer)
        if not ijk_root.is_dir():
            print(f"error: {ijk_root} is not a directory", file=sys.stderr)
            return 2
        macros, files = load_ffplay_macros(ijk_root)
        if macros is None:
            print(f"error: none of {', '.join(FFPLAY_FILES)} found under "
                  f"{ijk_root}", file=sys.stderr)
            return 2
        names = ", ".join(str(f.relative_to(ijk_root)) for f in files)
        print(f"# read {len(macros)} #define(s) from {len(files)} file(s): "
              f"{names}")
    elif not args.selftest:
        print("hint: pass --ijkplayer <tree> for the three-way check, or "
              "--selftest to run without one", file=sys.stderr)

    if args.selftest:
        failures = selftest_macros()
        for failure in failures:
            print(f"selftest FAIL: {failure}", file=sys.stderr)
        if failures:
            return 1
        print("# selftest OK: recursive #define, products, hex, unit "
              "canonicalisation; function-like macros rejected")

    rows = check(root, macros)
    if args.json:
        print(json.dumps(rows, indent=2, ensure_ascii=False))
        return 1 if any(r["status"] in FATAL for r in rows) else 0
    if args.emit:
        print(emit_block(rows))
        print()
    return print_report(rows)


if __name__ == "__main__":
    sys.exit(main())
